### PR TITLE
fix: make implement more consistent with design

### LINKED ISSUE #61: notice page
@di-void 
image

slight design inconsitenstes (check sizingf and padding)

### PR DESCRIPTION
**Pull request by di-void**
yada

### CODE REVIEW

**Comment by ellsurge** [comment]
same thing, fix the x padding to match the design

**Comment by di-void** [comment]
I have a hunch that my screen res might be a factor here😅

**Comment by di-void** [comment]
Done!

**Comment by di-void** [comment]
@ellsurge I've applied changes

**Pull request merged**
